
version: '3.8'

services:
  # Database PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: assenze_db
    restart: always
    environment:
      POSTGRES_DB: assenze_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d assenze_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Backend API Node.js
  api:
    build: ./backend
    container_name: assenze_api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=assenze_db
      - DB_USER=admin
      - DB_PASSWORD=admin123
      - NODE_ENV=production
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Frontend React
  frontend:
    build: .
    container_name: assenze_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://calendario.idrolab.local:8080
    depends_on:
      - api

volumes:
  db_data:
